openapi: 3.0.0
info:
  title: 'Stream API'
  description: 'Stream API'
  version: '1.0'
paths:
  /stream:
    get:
      tags:
        - Stream
      summary: 'Check if a stream exists by stream name'
      operationId: af06f8632b591945d1fc5685631cbf44
      parameters:
        -
          name: name
          in: query
          description: 'Stream name'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: ok
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/StreamNotFound'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
    post:
      tags:
        - Stream
      summary: 'Create a new stream'
      operationId: eda459c872260c56ea731525828d23ff
      parameters:
        -
          name: name
          in: query
          description: 'Stream name'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: ok
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '419':
          $ref: '#/components/responses/StreamAlreadyExists'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
    delete:
      tags:
        - Stream
      summary: 'Delete stream by stream name'
      operationId: c71c4de58375ad34a2c7f253952adf91
      parameters:
        -
          name: name
          in: query
          description: 'Stream name'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: ok
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/StreamNotFound'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
  /stream/from:
    get:
      tags:
        - Stream
      description: 'Retrieve stream events from included position with limit'
      operationId: retrieveStreamFromIncludedPosition
      parameters:
        -
          name: name
          in: query
          description: 'Stream name'
          required: true
          schema:
            type: string
        -
          name: from
          in: query
          description: 'from included stream position'
          required: true
          schema:
            type: integer
            minimum: 1
        -
          name: limit
          in: query
          description: 'limit the number of stream events, must be greater than from'
          required: true
          schema:
            type: integer
            minimum: 2
      responses:
        '200':
          $ref: '#/components/responses/StreamEvents'
        '204':
          $ref: '#/components/responses/NoStreamEventReturned'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/StreamNotFound'
        '500':
          $ref: '#/components/responses/500'
  /stream/from_to:
    get:
      tags:
        - Stream
      description: 'Retrieve stream events from included position to next included position'
      operationId: retrieveFromToStreamPosition
      parameters:
        -
          name: name
          in: query
          description: 'Stream name'
          required: true
          schema:
            type: string
        -
          name: from
          in: query
          description: 'from included stream position'
          required: true
          schema:
            type: integer
            minimum: 1
        -
          name: to
          in: query
          description: 'to included stream position, must be greater than from'
          required: true
          schema:
            type: integer
            minimum: 2
        -
          name: direction
          in: query
          description: 'sort stream by direction'
          required: true
          schema:
            type: string
            enum:
              - asc
              - desc
      responses:
        '200':
          $ref: '#/components/responses/StreamEvents'
        '204':
          $ref: '#/components/responses/NoStreamEventReturned'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/StreamNotFound'
        '500':
          $ref: '#/components/responses/500'
components:
  schemas:
    BodyData:
      properties:
        data:
          type: array
          items:
            properties:
              '':
                $ref: '#/components/schemas/StreamEvents'
            type: object
      type: object
    StreamEvents:
      required:
        - position
        - header
        - content
      properties:
        position:
          $ref: '#/components/schemas/StreamEventPosition'
        header:
          $ref: '#/components/schemas/StreamEventHeader'
        content:
          $ref: '#/components/schemas/StreamEventContent'
      type: object
    StreamEventPosition:
      required:
        - position
      properties:
        position:
          type: integer
          minimum: 1
      type: object
      additionalProperties: true
    StreamEventHeader:
      required:
        - __event_id
        - __event_time
        - __event_type
        - __aggregate_id
        - __aggregate_id_type
        - __aggregate_type
        - __aggregate_version
        - __internal_position
      properties:
        __event_id:
          type: string
          format: uuid
        __event_time:
          type: string
          format: date-time
        __event_type:
          type: string
        __aggregate_id:
          type: string
          format: uuid
        __aggregate_id_type:
          type: string
        __aggregate_type:
          type: string
        __aggregate_version:
          type: integer
          minimum: 1
        __internal_position:
          type: integer
          minimum: 1
        __event_causation_id:
          type: string
          format: uuid
        __event_causation_type:
          type: string
      type: object
      additionalProperties: true
    StreamEventContent:
      type: object
    Error:
      properties:
        message:
          type: string
        code:
          type: integer
      type: object
    ValidationError:
      type: array
      items: {  }
  responses:
    StreamEvents:
      description: 'Stream events'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BodyData'
    NoStreamEventReturned:
      description: 'Stream exists but no stream event returned'
    '422':
      description: 'Validation failed'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    '401':
      description: 'Authentication failed'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: 'Authorization failed'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    StreamNotFound:
      description: 'Stream not found'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    StreamAlreadyExists:
      description: 'Stream already exists'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: 'Internal error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
tags:
  -
    name: Stream
    description: 'Stream API'
